spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8"
    username: root
    password: root
  profiles:
    active: default
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 1220   # 连接超时时间（毫秒）
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    username: 821646177@qq.com
    password: myabknnqmsdrbdgi
    port: 587
    protocol: smtp
    default-encoding: utf-8

mybatis:
  typeAliasesPackage: com.example.demo.business.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
mapper:
  mappers: com.example.demo.mappers.MyMapper
  identity: MYSQL



server:
  port: 8080
  servlet:
    context-path: /business


pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  supportMethodsArguments: true

gwf:
  name: 1111
swagger:
  enabled: true

logging:
  config: classpath:mybatis/logback.xml








